version: '3'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0 --port=8000
    working_dir: /myapp
    volumes: 
      - ./:/myapp
    ports: 
      - "8000:8000"
    depends_on: 
      - database
    tty: true
    stdin_open: true
    networks: 
      - app-network

  database:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports: 
      - "33060:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_DATABASE: elearning
      MYSQL_PASSWORD: homestead
    volumes: 
      - mysqldata:/var/lib/mysql:rw,delegated
    networks: 
      - app-network

volumes: 
  mysqldata:

networks: 
  app-network:
    driver: bridge
    